### ISSUE TITLE
CDK Hotswap Feature : AWS::CloudFront::Distribution Attribute Support

### ISSUE THREAD

**Issue by bellomal** [aws/aws-cdk-cli#864]
### Describe the bug

When doing a hotswap deployment of an ECS instance, the following error was thrown:

```
Could not perform a hotswap deployment, because the CloudFormation template could not be resolved: We don't support attributes of the 'AWS::CloudFront::Distribution' resource. This is a CDK limitation. Please report it at https://github.com/aws/aws-cdk/issues/new/choose
```

Looking at the `cdk synth` output (check current behavior), we can see that one of the ECS instance environment variables is a Distribution DomainName.

Opening this ticket as instructed by the error message. If this isn't the correct place for this ticket, let me know and I can reroute it to the appropriate location.

### Expected Behavior

The hotswap deployment to succeed, since the Distribution DomainName has not changed.

### Current Behavior

The hotswap deployment fails. As far as I can tel, this is because the DomainName attribute of the Distribution resource is not supported. See the below snippet of the `cdk synth` result for more context.

```
  ServiceClusterTaskDefF486EB2A:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Cpu: 4096
          Environment:
            - Name: STAGE
              Value: beta
            - Name: APPLICATION_NAME
              Value: Service
            - Name: ENDPOINT
              Value:
                Fn::GetAtt:
                  - ASVSelectionServiceCuratedChannelscuratedChannelDistribution0D56EA6F
                  - DomainName
```

### Reproduction Steps

Run a hotswap deployment for an ECS instance that contains a Distribution attribute in it's definition.

### Possible Solution

Similar to https://github.com/aws/aws-cdk/issues/21320, allow hotswap to tolerate the use of this attribute if it's value hasn't been changed.

### CDK CLI Version

2.127.0

### Node.js Version

14.x

### OS

Linux

### Language

TypeScript
